[book]
title = "Casting SPELs in LFE"
author = "Duncan McGreggor"
description = "The LFE Edition of the Classic Lisp Comic Book"
language = "en"

[build]
build-dir = "docs"

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "lfe-pdp"
preferred-dark-theme = "lfe-pdp"
additional-css = ["css/custom.css"]
google-analytics = "UA-38274766-4"
git-repository-url = "https://github.com/lfe/casting-spels/"
[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
